### ISSUE TITLE
Rule executer - remove channel feature

### ISSUE THREAD

**Issue by Sandy-at-Tazama** [frmscoe/rule-executer#132]
## User Story Statement
**As a** Tazama system operator
**I want** to remove the channel feature
**so that** the system is as simple as possible to maintain and configure for an inexperienced user; and
**so that** the system performs as fast as possible at the lowest possible cost

## Acceptance Criteria 
1. Bump the FRMS-coe-lib version
2. Bump the FRMS-coe-startup-lib
3. The outgoing payload from the CRSP  was updated to remove the channel feature ( see CRSP - remove channel feature [#124](https://github.com/frmscoe/channel-router-setup-processor/issues/124)) and the object was redefined. The object must be redefined across all subsequent processors i.e. rule-executer
4. Regression test against rule-001 to ensure that there is no impact on the rule processor related to the change 
5. Create/Update rule executer documentation as follows:
## Overview/Description/Introduction
What does the processor do?
## Inputs (Docstring documentation)
What does the processor need?
## Internal process flow (diagram, with descriptions)
How does the processor work?
## Outputs (linked to diagram exit points)
What does the processor deliver?
## Environment variables (table)
How can the processor behaviour be configured?
## Deployment
How is the processor deployed?
## Operation
How is the processor operated? (Stopped, Restarted, etc)
## Troubleshooting
What are typical issues and their remedies

see TMS-configuration - remove channel feature [#2](https://github.com/frmscoe/tms-configuration/issues/2)

## Assumptions
1. Only the rule-executor needs to be updated to remove the channel feature and not each rule-processor individually
3. If rule processors interrogate the network map, the processing must be updated

**Comment by rtkay123** [comment]
Related to: https://github.com/frmscoe/rule-executer/issues/135

Upstream changes to frms-coe-lib include a version that removes `channel` and `result`.
