### ISSUE TITLE
Rule Executer - remove true/ false rule result outcome

### ISSUE THREAD

**Issue by Sandy-at-Tazama** [frmscoe/rule-executer#135]
## Background

The impact of rule “Result”: false/true on the typology processing is artificial and the specific “subRuleRef” is already sufficiently unique to determine the weighting in the typology processor. https://github.com/frmscoe/General-Issues/issues/351

## User Story Statement

**As a** Tazama system operator
**I want** to remove the true and false rule outcomes; and
**I want** to replace the true/false weighting attributes with a weighting attribute
**so that** the system is as simple as possible to maintain and configure for an inexperienced user; and
**so that** the system performs as fast as possible at the lowest possible cost

## Acceptance Criteria
1. Bump the FRMS-coe-lib version
2. Bump the FRMS-coe-startup-lib
2. Remove the rule config outcome ('true' or 'false') attribute
3. Changes to the rule results class/object type
4. Changes to the result payload structure out of the rule processor
5. Regression test against rule-001 to ensure that there is no impact on the rule processor related to the change
6. Regression test against rule-078 to ensure that there is no impact on the rule processor related to the change for a cased `determineOutcome` function call
7. Update documentation

## Assumptions
1. Only the rule-executor needs to be updated to remove the rule result (True/false) and not each rule-processor individually

**Comment by rtkay123** [comment]
We will have to update the rules for this change in particular:

```js
 determineOutcome: (
    value: number,
    ruleConfig: RuleConfig,
    ruleResult: RuleResult, // This rule result defined in the library is includes true/false
  ) => RuleResult,
```

Typescript also reflects the same:
```
 Property 'result' is missing in type 'import("/path/to/rule-executer/node_modules/@frmscoe/frms-coe-lib/lib/interfaces/rule/RuleResult").RuleResult' but required in type 'import("/path/to/rule-executer/node_modules/rule/node_modules/@frmscoe/frms-coe-lib/lib/interfaces/rule/RuleResult").RuleResult'.
```
Tested with `rule-901`
