### ISSUE TITLE
Log Rule Result Reasons

### ISSUE THREAD

**Issue by rtkay123** [frmscoe/rule-executer#88]
## Story statement

**As an** FRMS Platform user/developer,
**I want** the rule executor to log the `reason` for a particular rule's outcome,
**So that** the rules themselves don't have that responsibility so that we have guaranteed consistency

## Acceptance criteria
1. Rules (libraries) can log the specifics (to them) of that particular rule
2. The rule-executor logs the `reason` before it's removed from the message send to the next processor
3. Rule executor logs just before it calls the rule library*

**Comment by Justus-at-Tazama** [comment]
End-to-end test update:

![image](https://github.com/frmscoe/rule-executer/assets/123470803/e156f251-c261-499d-9cad-66b669a4ae81)
